name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise the token used is the GITHUB_TOKEN instead of personal
          persist-credentials: false
          # Otherwise will fail to push refs to destination repo
          fetch-depth: 0

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Generate packages.json file from the package set
        run: |
          # Set Git configuration to the GitHub Action user, which won't trigger
          # subsequent runs of this Action.
          git config --local pull.ff only
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull

          # Generate the new packages.json file
          nix-shell --run 'make generate'

          # Run verification steps
          nix-shell --run 'make verify-registry'
          nix-shell --run 'make test-psc-package'

          # Only commit if the prior commands dirtied the working tree
          git diff --quiet || git commit -a -m "Update packages.json."

      - name: Push changes if necessary
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - uses: actions/cache@v2
        with:
          path: |
            output
            .psc-package
          key: ${{ runner.os }}-build-products

      - run: nix-shell --run 'cd src && spago verify-set'
