name: Build the package set

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Generate packages.json file from the package set
        id: generate-packages
        run: |
          nix-shell --run 'make generate'
          echo ::set-output name=modified::$(if git diff --quiet; then echo "false"; else echo "true"; fi)

      - name: Verify all packages are in the registry
        run: nix-shell --run 'make verify-registry'

      - name: Verify all packages are compatible with psc-package
        run: nix-shell --run 'make test-psc-package'

      - uses: actions/cache@v2
        with:
          path: |
            output
            .psc-package
          key: ${{ runner.os }}-build-products

      - name: Verify all packages in the set build together
        # This verification step is expensive, and we can skip the check if the
        # package set is unchanged (e.g. generating a new packages.json file did
        # not produce any changes to the package set).
        if: steps.generate-packages.outputs.modified == 'true'
        run: nix-shell --run 'cd src && spago verify-set'

      - name: Commit and push modified files
        if: steps.generate-packages.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git pull --ff-only
          git commit -am "Update packages.json file"
          git push
